### ISSUE TITLE
Back from submenu

### ISSUE THREAD

**Issue by jcvillegasfernandez** [forntoh/LcdMenu#1]
When returning from the submenu it does not return to the same line from which it was called

**Comment by forntoh** [comment]
I will add this feature in a future release

**Comment by forntoh** [comment]
@jcvillegasfernandez  You can pull the `experimental` branch and test if this feature works as expected

**Comment by jcvillegasfernandez** [comment]
I tried experimental history version and it works

**Comment by forntoh** [comment]
> I tried experimental history version and it works

Thanks  a lot, I will update the master branch

**Comment by kulverstukas1** [comment]
Doesn't seem to work for me. When I go back in the menu, I get throw onto the first menu item, not from the one I came in.

**Comment by forntoh** [comment]
Oh... I didn't merge `experimental `with `master`

**Comment by kulverstukas1** [comment]
Tested. Working now.
