### ISSUE TITLE
[BUG]: Issue with toggle Backlight in Example 03 Callbacks v3.2.0

### ISSUE THREAD

**Issue by maansch** [forntoh/LcdMenu#113]
### What happened?

Unsing ITEM_TOGGLE("Backlight", toggleBacklight),  
after executing cmd backlight LCD goes OFF and switch back to ON

in v3.0.0 it works
br
Marc-Andre

### Version

3.2.0

### What environment are you seeing the problem in?

Arduino

### Board type

ESP-32 Development-Board

### Relevant log output

```shell
none
```

**Comment by forntoh** [comment]
Please check if this issue is still reproducible in 3.3.0
