### ISSUE TITLE
[NEW-FEATURE] - LCD menu avec encodeur rotatif KY-040

### ISSUE THREAD

**Issue by Sebidarkprince** [forntoh/LcdMenu#118]
### Is your feature request related to a problem?

Bonjour,
Merci pour le travail que vous avez effectué sur cette bibliothèque, il va grandement me simplifier mon projet de doseuse à miel.

Je souhaiterais savoir s'il est possible d'utiliser votre bibliothèque avec un encodeur rotatif type KY-040, j'ai essayé de le faire, mais pour le moment les résultats ne sont pas probants (mes capacités en programmation sont très limitées)
Voici la bibliothèque que j'utilise pour mon encodeur rotatif : https://github.com/igorantolic/ai-esp32-rotary-encoder/blob/master/README_old.md

Merci d'avance pour ton aide

Sébastien 

### Describe the solution you'd like?

Fonctionnement de la bibliothèque LCDmenu avec encodeur rotatif KY-040

**Comment by forntoh** [comment]
Someone using it with a Rotatory encoder
https://github.com/forntoh/LcdMenu/discussions/29#discussioncomment-915350

I don't have one, so I can't help you. However with this library, you can use ANY input device of your choice, you just have to know how to integrate it with the library.
