### ISSUE TITLE
ITEM_COMMAND not working 

### ISSUE THREAD

**Issue by rozrabiak** [forntoh/LcdMenu#128]
### What happened?

```cpp
ITEM_COMMAND("EXIT MENU", exitMenu));  //close menu and off backlight

void exitMenu()
{
  Serial.println("working");
  menu.resetMenu();
  menu.hide();
}
```

And function not invoking when presing ENTER.
But I can navigate throught menu, I can enter to submenu using ENTER.

Arduino & STM32F4.
Any ideas?

### Version

3.3.2

### What environment are you seeing the problem in?

Platform IO

### Board type

blackpill STM32F4ccu6

**Comment by forntoh** [comment]
Please make sure that your imports are correctly placed

see https://lcdmenu.forntoh.dev/usage

**Comment by hapiel** [comment]
This could be marked more clearly, I've been debugging for 3 hours before I found this!
