### ISSUE TITLE
Editing documentation

### ISSUE THREAD

**Issue by hapiel** [forntoh/LcdMenu#132]
Is the documentation also in a git? I wanted to propose an edit to a page: 

https://lcdmenu.forntoh.dev/examples/submenu

This page fails to mention that `#include <ItemSubMenu.h>` needs to be, well..., included!

**Comment by hapiel** [comment]
Another thing to add somewhere is that users need to install marcoschwartz/LiquidCrystal_I2C@^1.1.4 for it to work

**Comment by forntoh** [comment]
@hapiel See the docs branch https://github.com/forntoh/LcdMenu/tree/docs
