### ISSUE TITLE
[BUG]: Down-scroll arrow works incorrect (or at least differently from the Up-scroll one)

### ISSUE THREAD

**Issue by anonymouspenguin000** [forntoh/LcdMenu#167]
### What happened?

Scrolling arrows should appear only in case if there are available menu items behind the menu's visible area (they show if you can still scroll above/below). The **up-scroll** arrow works **properly**: the arrow **doesn't app**ear if there **aren't** available items above, perfect. But the **down-scroll** arrow **doesn't dis**appear until the **cursor** is at the very bottom, even if the menu at very bottom.

To understand the issue better: the **up-scroll** arrow shows available items above **menu** and the **down-scroll** one shows available items below **cursor**.

It's not a very critical bug, but I would like it to be fixed. Maybe later I will create a pull request to this repo to fix this issue.

==> [Explaining video](https://www.youtube.com/watch?v=tPc7PFqSB_g) <==

### Version

3.5.4

**Comment by forntoh** [comment]
@anonymouspenguin000 I'm waiting to review your PR, contributions are always welcomed here ☺️
