### ISSUE TITLE
Menu command processor helper for rotatory encoder

### ISSUE THREAD

**Issue by forntoh** [forntoh/LcdMenu#178]
### Describe the solution you'd like?

Would be nice if the library had a helper which handles menu navigation using rotatory encoder.

This helper function can then be used in the loop

**Comment by ShishkinDmitriy** [comment]
Hi, 

I also tried to combine this with RotaryEncoder and found this solution:
```c++
void loop() {
    rotaryEncoder.tick();
    switch (rotaryEncoder.getDirection()) {
        case RotaryEncoder::Direction::CLOCKWISE:
            menu.down();
            menu.right();
            break;
        case RotaryEncoder::Direction::COUNTERCLOCKWISE:
            menu.up();
            menu.left();
            break;
        default: {
            break;
        }
    }
    if (button.pressed()) {
        if (menu.lcd.getEditModeEnabled()) {
          menu.back();
        } else {
          menu.enter();
        }
    }
    lcdAdapter.updateTimer();
}
```
On single rotation you make [both `down()` and `right`] or [both `up()` and `left()`]. Depending on the state of menu it will be either navigation or value change.
Hope it will be usefull.

Best regards,
Dmitry
