### ISSUE TITLE
[BUG]: Dependencies in the file "library.properties"

### ISSUE THREAD

**Issue by RoneFRANCE** [forntoh/LcdMenu#203]
### What happened?

Hello,

Under wokwi using LCDMENU.h library which refers to LiquidCrystal_I2C library, I am getting this answer :
Error installing LcdMenu: No valid dependencies solution found: dependency 'LiquidCrystal_I2C' is not available

How could we get solved this problem on wokwi please ?

Thank you

Erwan

### Version

4.1.0

**Comment by forntoh** [comment]
@RoneFRANCE Have you tried manually installing the LiquidCrystal_I2C library?

**Comment by forntoh** [comment]
Please also check this conversation #168, the creator closed it so you might find a solution there.

**Comment by RoneFRANCE** [comment]
I am not able to add libraries manually in wokwi as I don't have the paid version

**Comment by forntoh** [comment]
@RoneFRANCE @ZanPekosak 

This should be solved in [v4.2.0](https://github.com/forntoh/LcdMenu/releases/tag/4.2.0) by #215, you will just need to install all dependencies manually.
