### ISSUE TITLE
Backlight support for non-I2C

### ISSUE THREAD

**Issue by thijstriemstra** [forntoh/LcdMenu#21]
I had to hack and add the last 2 parameters to `new LiquidCrystal` in order to get the backlight working.

```
#ifndef USE_STANDARD_LCD
        uint8_t lcd_Addr, MenuItem* menu) {
        lcd = new LiquidCrystal_I2C(lcd_Addr, maxCols, maxRows);
        lcd->init();
        lcd->backlight();
#else
        uint8_t rs, uint8_t en, uint8_t d0, uint8_t d1, uint8_t d2, uint8_t d3,
        MenuItem* menu) {
        this->lcd = new LiquidCrystal(rs, en, d0, d1, d2, d3, DisplayBacklightPin, POSITIVE); // <---
        this->lcd->begin(maxCols, maxRows);
#endif
```

would be nice if this could be supported in the library.

**Comment by forntoh** [comment]
What are the possible values for `DisplayBacklightPin`, `POSITIVE`?
Are you using the official `LiquidCrystal` library by Arduino?

**Comment by thijstriemstra** [comment]
I'm using `fmalpartida/LiquidCrystal` and `DisplayBacklightPin` is a var from my project with value 5. `POSITIVE` is a constant from that LiquidCrystal library. e.g. `t_backlightPol pol = POSITIVE`.

**Comment by thijstriemstra** [comment]
Should I make PR for this fix @forntoh?

**Comment by thijstriemstra** [comment]
> Should I make PR for this fix @forntoh?

see #75
