### ISSUE TITLE
[BUG]: DEBUG mode not working

### ISSUE THREAD

**Issue by forntoh** [forntoh/LcdMenu#217]
### What happened?

Expected: Adding #define DEBUG to the top of the file, I expect to see logs in the terminal
Actual: No logs printed to the terminal for `UP`, `DOWN` `ENTER` etc

The only log I saw was `#CMD# Opening screen...`

Those logs will be necessary later when for doing CI checks.
https://docs.wokwi.com/wokwi-ci/getting-started

### Version

_5.0.0 (Unreleased)_

### What environment are you seeing the problem in?

Platform IO

### Board type

AVR

**Comment by ShishkinDmitriy** [comment]
Can `#define DEBUG` be added on top of `utils/utils.h`?
Right now the problem is that some classes have references to each other. And it's not possible to include each other.
That's why I have to move some implementations into `cpp`.

**Comment by ShishkinDmitriy** [comment]
Think I found.
Need to add `build_flags = -D DEBUG` into `platformio.ini`.
It will be applied for all at the beginning.

**Comment by forntoh** [comment]
That works, I'll add it and add logs to MenuScreen.

**Comment by ShishkinDmitriy** [comment]
Probably it's possible to create multiple envs, one with, one without debug.
