### ISSUE TITLE
[NEW-FEATURE] - Support for esp32

### ISSUE THREAD

**Issue by almofada1** [forntoh/LcdMenu#245]
### Is your feature request related to a problem?

Yes, I tried to find other libraries as good as yours for esp32 but couldn't so this is my last resort

### Describe the solution you'd like?

Support for esp32

### Describe alternatives you've considered

None, so simple and straight forward, you cant find it anywhere else

**Comment by forntoh** [comment]
Thanks for the feature request, I'm happy that you love the library even without trying it out, leaving a ⭐️ would be great 😊, I will investigate adding support for ARM boards until next weekend. My main focus was AVR boards, but the library is mature enough for it to expand to other boards.

**Comment by forntoh** [comment]
@almofada1 FYI Support for ESP32 boards added in [v5.3.0](https://lcdmenu.forntoh.dev/reference/changelog.html#lcdmenu-v5-3-0)

**Comment by almofada1** [comment]
Thank you very much. Life saver!
