### ISSUE TITLE
MenuScreen.h  with ItemCommand

### ISSUE THREAD

**Issue by kimbrussow** [forntoh/LcdMenu#268]
I have built a basic menu and subMenus. All works fantastic using
MENU_SCREEN(settingsScreen, settingsItems,
    ITEM_BASIC("Pick something"),
    ITEM_WIDGET(
        "Brightness",
        callbackInt,
        WIDGET_RANGE(90, 5, 50, 100, "%d%%", 1)),
      ITEM_WIDGET(
        "Speed",
        callbackIntS,
        WIDGET_RANGE(90, 5, 75, 100, "%d%%", 1)),....

however using
MENU_SCREEN(mainScreen, mainItems,
    ITEM_SUBMENU("Settings", settingsScreen),
    ITEM_COMMAND("Item 1", []() {
    DisplayPattern1;
    },

even adding #include <ItemCommand.h>
I cannot get ITEM_COMMAND to even compile. None of the examples show usage of ITEM_COMMAND 
Any Ideas?

**Comment by forntoh** [comment]
https://lcdmenu.forntoh.dev/overview/items/command.html
