### ISSUE TITLE
generatemenu compile error

### ISSUE THREAD

**Issue by youxiaojie** [forntoh/LcdMenu#32]
Arduino: 1.8.15 (Linux), Board: "Arduino Uno"

arduino-builder -dump-prefs -logger=machine -hardware /usr/share/arduino/hardware -hardware /home/allan/.arduino15/packages -tools /usr/share/arduino/hardware/tools/avr -tools /home/allan/.arduino15/packages -libraries /home/allan/Arduino/libraries -fqbn=arduino:avr:uno -ide-version=10815 -build-path /tmp/arduino_build_733096 -warnings=default -build-cache /tmp/arduino_cache_980456 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/home/allan/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/allan/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.avr-gcc.path=/home/allan/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/allan/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -verbose /home/allan/Arduino/GenerateMenu/GenerateMenu.ino
arduino-builder -compile -logger=machine -hardware /usr/share/arduino/hardware -hardware /home/allan/.arduino15/packages -tools /usr/share/arduino/hardware/tools/avr -tools /home/allan/.arduino15/packages -libraries /home/allan/Arduino/libraries -fqbn=arduino:avr:uno -ide-version=10815 -build-path /tmp/arduino_build_733096 -warnings=default -build-cache /tmp/arduino_cache_980456 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/home/allan/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.arduinoOTA-1.3.0.path=/home/allan/.arduino15/packages/arduino/tools/arduinoOTA/1.3.0 -prefs=runtime.tools.avr-gcc.path=/home/allan/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino7.path=/home/allan/.arduino15/packages/arduino/tools/avr-gcc/7.3.0-atmel3.6.1-arduino7 -verbose /home/allan/Arduino/GenerateMenu/GenerateMenu.ino
Using board 'uno' from platform in folder: /usr/share/arduino/hardware/arduino/avr
Using core 'arduino' from platform in folder: /usr/share/arduino/hardware/arduino/avr
Build options changed, rebuilding all
Detecting libraries used...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_BoseWave.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Denon.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Dish.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_DistanceProtocol.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_JVC.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Kaseikyo.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_LG.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Lego.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_MagiQuest.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_NEC.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Pronto.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_RC5_RC6.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Samsung.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Sony.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Template.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/Arduino-IRremote-master/src/ir_Whynter.cpp" -o "/dev/null"
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/home/allan/Arduino/libraries/LiquidCrystal/src/LiquidCrystal.cpp" -o "/dev/null"
Generating function prototypes...
"/usr/bin/avr-g++" -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing  -flto -w -x c++ -E -CC -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/tmp/arduino_build_733096/preproc/ctags_target_for_gcc_minus_e.cpp"
"/usr/bin/arduino-ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "/tmp/arduino_build_733096/preproc/ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"/usr/bin/avr-g++" -c -g -Os  -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=10815 -DARDUINO_AVR_UNO -DARDUINO_ARCH_AVR   "-I/usr/share/arduino/hardware/arduino/avr/cores/arduino" "-I/usr/share/arduino/hardware/arduino/avr/variants/standard" "-I/home/allan/Arduino/libraries/LcdMenu/src" "-I/home/allan/Arduino/libraries/Arduino-IRremote-master/src" "-I/home/allan/Arduino/libraries/LiquidCrystal/src" "-I/home/allan/Arduino/libraries/Neotimer/src" "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp" -o "/tmp/arduino_build_733096/sketch/GenerateMenu.ino.cpp.o"
In file included from /home/allan/Arduino/GenerateMenu/GenerateMenu.ino:25:0:
/home/allan/Arduino/libraries/Neotimer/src/neotimer.h:41:2: warning: ‘typedef’ was ignored in this declaration
  };
  ^
/home/allan/Arduino/GenerateMenu/GenerateMenu.ino: In function ‘void setup()’:
GenerateMenu:59:41: error: no matching function for call to ‘LcdMenu::setupLcdWithMenu(int, MenuItem*&)’
     menu.setupLcdWithMenu(0x27, mainMenu);
                                         ^
In file included from /home/allan/Arduino/GenerateMenu/GenerateMenu.ino:24:0:
/home/allan/Arduino/libraries/LcdMenu/src/LcdMenu.h:309:10: note: candidate: void LcdMenu::setupLcdWithMenu(uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t, MenuItem*)
     void setupLcdWithMenu(
          ^
/home/allan/Arduino/libraries/LcdMenu/src/LcdMenu.h:309:10: note:   candidate expects 7 arguments, 2 provided
Using library LcdMenu at version 2.0.0-beta.2 in folder: /home/allan/Arduino/libraries/LcdMenu 
Using library Arduino-IRremote-master at version 3.4.0 in folder: /home/allan/Arduino/libraries/Arduino-IRremote-master 
Using library LiquidCrystal at version 1.0.7 in folder: /home/allan/Arduino/libraries/LiquidCrystal 
Using library Neotimer at version 1.1.6 in folder: /home/allan/Arduino/libraries/Neotimer 
exit status 1
no matching function for call to ‘LcdMenu::setupLcdWithMenu(int, MenuItem*&)’

**Comment by forntoh** [comment]
`GenerateMenu` discontinued (will be removed)
