### ISSUE TITLE
Enhancement: make `cursorPosition` public

### ISSUE THREAD

**Issue by jiriks74** [forntoh/LcdMenu#52]
Hi, I'm working on a menu that work's like this:
If there is no input for certain amount of time the menu is hidden and info screen is shown (state of pumps, etc) and after longer amount of time backlight will be turned off.
Then if user inputs if backlight is on and infoscreen is shown, menu shows, if even the backlight is off, it will turn on on the first keypress and the menu will be shown on the second keypress.

Now for the problem. When the menu is shown again the cursor has the position from the last time someone used it. I'd set `cursorPosition = 1` to do it, but you've set it as private. This would allow people to reset the cursor position and setup keyboard shortcuts, etc

**Comment by forntoh** [comment]
FYI @jiriks74 There's now a setter and getter for `cursorPosition`
